# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d786c63eb302d0fe091ed158aa04d603ca5e46aaac444bfaa047be2bec56bf47e1aada7978475030024c6c48f9dff707473be10e17971ff96c3dc89af1f5e57b

test:
  secret_key_base: 9d8bf788d8a25f178d87c6d4a66c354497c815fc50e8ec877ddf656dca4c1637e72ac9418184810933fe67c99bf2a5cd1b9648a94ca82e1f7efaf6e6a49236cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
